extra steps

diff --git a/.github/workflows/azure-webapps-node.yml b/.github/workflows/azure-webapps-node.yml
--- a/.github/workflows/azure-webapps-node.yml
+++ b/.github/workflows/azure-webapps-node.yml
@@ -37,11 +37,23 @@ jobs:
       - name: Build the Project
         run: npm run build
 
+      - name: Verify Standalone Build
+        run: |
+          if [ -f ./build/standalone/server.js ]; then
+            echo "Standalone server.js found."
+            ls -la ./build/standalone/
+          else
+            echo "Standalone server.js not found."
+            ls -la ./build/
+            exit 1
+          fi
+
       - name: Upload Build Artifacts
         uses: actions/upload-artifact@v4
         with:
           name: build-artifacts
-          path: ./build/standalone/
+          path: ./build/  # Upload de gehele build map
+
   deploy:
     runs-on: ubuntu-latest
     needs: build
@@ -53,10 +65,13 @@ jobs:
           name: build-artifacts
           path: ./deploy_artifacts/
 
+      - name: List Deploy Artifacts
+        run: ls -la ./deploy_artifacts/build/standalone/
+
       - name: Deploy to Azure Web App
         uses: azure/webapps-deploy@v3
         with:
           app-name: ${{ env.WEBAPP_NAME }}
           slot-name: "Production"
           publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
-          package: ./deploy_artifacts/
+          package: ./deploy_artifacts/build/  # Deploy de build map
